### ISSUE TITLE
IBC_ReadOnlyApi = no not working

### ISSUE THREAD

**Issue by thunderwin** [extrange/ibkr-docker#57]
I wanna uncheck readyonly_api by default. but
 IBC_ReadOnlyApi = no not working

**Comment by extrange** [comment]
The default behavour of IBC should already uncheck `ReadOnlyApi`, so you don't actually have to set that variable.

However, if you do set it, make sure you put `no` in quotes, i.e.

```yaml

IBC_ReadOnlyApi: 'no'
```

This is because the [YAML format reads strings](https://github.com/docker/compose/issues/1788) such as `yes` and `no` as `True` and `False` respectively.

Do let me know if this works.

I will update the documentation.
